import type { Canonical } from "../types/core";

export const CANONICALS: Canonical[] = [
  // --- Primary canonicals (existing) ---
  {
    id: "onboarding_completion",
    domain: "onboarding",
    question: "When is onboarding considered complete?",
    intent: "decision_readiness",
    primaryAnswerId: "a_onboarding_completion_primary",
    variations: [
      "Is onboarding done after setup?",
      "Can we close onboarding?",
      "is onboarding complete?",
      "is onboarding complete",
      "when is onboarding complete?",
      "Are we done with onboarding yet?",
      "What defines successful onboarding?",
    ],
    keywords: ["onboarding complete", "close onboarding", "done onboarding", "after setup", "complete onboarding"],
  },
  {
    id: "kickoff_outcomes",
    domain: "onboarding",
    question: "What should come out of the kickoff call?",
    intent: "alignment_check",
    primaryAnswerId: "a_kickoff_outcomes_primary",
    variations: [
      "What do I need to cover in the kickoff?",
      "How do I know the kickoff went well?",
      "Expected kickoff outcomes?",
      "What should be clarified after kickoff?",
    ],
    keywords: ["kickoff", "kick off", "kick-off", "kickoff call", "kickoff outcomes"],
  },
  {
    id: "onboarding_stalled",
    domain: "onboarding",
    question: "What if onboarding is delayed or stalled?",
    intent: "corrective_action",
    primaryAnswerId: "a_onboarding_stalled_primary",
    variations: [
      "Onboarding is stuck. What now?",
      "What if onboarding stalls?",
      "Customer is not progressing during onboarding",
      "Onboarding delayed, what should I do?",
    ],
    keywords: ["stalled", "stuck", "delayed", "delay", "not progressing", "onboarding stalled", "onboarding stuck"],
  },
  {
    id: "risk_detection",
    domain: "risk",
    question: "How do we know if an account is at risk?",
    intent: "risk_assessment",
    primaryAnswerId: "a_risk_detection_primary",
    variations: [
      "Is this account risky?",
      "I think this customer might churn",
      "Usage dropped, should I worry?",
      "Customer seems disengaged — what does it mean?",
    ],
    keywords: ["at risk", "risky", "churn", "disengaged", "usage dropped", "health", "risk signals"],
  },
  {
    id: "risk_response",
    domain: "risk",
    question: "What should I do when I suspect an account is at risk?",
    intent: "risk_response",
    primaryAnswerId: "a_risk_response_primary",
    variations: [
      "What do I do if I suspect risk?",
      "How do I react to risk without escalating?",
      "Customer might churn, what now?",
      "What actions should I take first?",
    ],
    keywords: ["what should i do", "actions", "mitigate", "prevent churn", "risk response", "before escalation"],
  },
  {
    id: "risk_escalation",
    domain: "risk",
    question: "When and how should we escalate a high-risk account?",
    intent: "escalation_boundary",
    primaryAnswerId: "a_risk_escalation_primary",
    variations: [
      "Should I escalate this account?",
      "When do we involve leadership?",
      "How do I escalate without alarming the customer?",
      "What qualifies as high-risk escalation?",
    ],
    keywords: ["escalate", "escalation", "involve leadership", "exec", "high risk"],
  },

  // --- Follow-up canonicals (new) ---
  {
    id: "onb_first_value",
    domain: "onboarding",
    question: "What counts as first value?",
    intent: "clarify_definition",
    primaryAnswerId: "a_onb_first_value",
    variations: [
      "What is first value?",
      "What counts as first verified value?",
      "How do we define first value in onboarding?",
    ],
    keywords: ["first value", "verified value", "value milestone"],
  },
  {
    id: "onb_to_adoption",
    domain: "onboarding",
    question: "When do we transition from onboarding to adoption?",
    intent: "lifecycle_transition",
    primaryAnswerId: "a_onb_to_adoption",
    variations: [
      "When does onboarding end and adoption start?",
      "Move from onboarding to adoption",
      "What happens after onboarding?",
    ],
    keywords: ["transition", "adoption", "after onboarding"],
  },
  {
    id: "onb_document_completion",
    domain: "onboarding",
    question: "How do we document onboarding completion?",
    intent: "documentation",
    primaryAnswerId: "a_onb_document_completion",
    variations: [
      "How do we document onboarding completion?",
      "What should we record when onboarding is complete?",
      "How do we mark onboarding complete?",
    ],
    keywords: ["document", "record", "mark complete", "onboarding completion"],
  },

  {
    id: "kickoff_red_flags",
    domain: "onboarding",
    question: "What are common kickoff red flags?",
    intent: "risk_prevention",
    primaryAnswerId: "a_kickoff_red_flags",
    variations: [
      "Kickoff red flags",
      "What are warning signs in kickoff?",
      "How do I know kickoff went badly?",
    ],
    keywords: ["red flags", "warning", "kickoff", "risk"],
  },
  {
    id: "kickoff_document",
    domain: "onboarding",
    question: "What should be documented after the kickoff?",
    intent: "documentation",
    primaryAnswerId: "a_kickoff_document",
    variations: [
      "What should we write down after kickoff?",
      "Kickoff documentation",
      "What do we capture after kickoff?",
    ],
    keywords: ["document", "notes", "owners", "timeline", "kickoff"],
  },
  {
    id: "kickoff_success_plan",
    domain: "onboarding",
    question: "How does the kickoff feed into the success plan?",
    intent: "framework_link",
    primaryAnswerId: "a_kickoff_success_plan",
    variations: [
      "How does kickoff connect to the success plan?",
      "Kickoff to success plan",
      "How do we translate kickoff into a plan?",
    ],
    keywords: ["success plan", "kickoff", "objectives", "initiatives"],
  },
  {
    id: "kickoff_who_involved",
    domain: "onboarding",
    question: "Who needs to be involved in the kickoff call?",
    intent: "stakeholders",
    primaryAnswerId: "a_kickoff_who_involved",
    variations: [
      "Who should attend kickoff?",
      "Kickoff stakeholders",
      "Who needs to be in the kickoff call?",
    ],
    keywords: ["stakeholders", "attendees", "kickoff"],
  },

  {
    id: "stall_root_cause",
    domain: "onboarding",
    question: "How do we identify the root cause of onboarding delays?",
    intent: "diagnosis",
    primaryAnswerId: "a_stall_root_cause",
    variations: [
      "How do we find the root cause of onboarding delays?",
      "Why is onboarding delayed?",
      "How do we diagnose onboarding issues?",
    ],
    keywords: ["root cause", "diagnose", "onboarding delays", "blocker"],
  },
  {
    id: "stall_reset_timeline",
    domain: "onboarding",
    question: "How do we reset onboarding timelines with the customer?",
    intent: "customer_comms",
    primaryAnswerId: "a_stall_reset_timeline",
    variations: [
      "How do we reset the onboarding timeline?",
      "How do we rebaseline onboarding dates?",
      "Customer timeline changed during onboarding",
    ],
    keywords: ["reset timeline", "rebaseline", "timeline", "onboarding delayed"],
  },

  {
    id: "risk_check_first",
    domain: "risk",
    question: "What should I check first when I suspect risk?",
    intent: "diagnosis",
    primaryAnswerId: "a_risk_check_first",
    variations: [
      "What should I check first when risk appears?",
      "First checks for account risk",
      "How do I validate risk quickly?",
    ],
    keywords: ["check first", "validate risk", "triage", "signals"],
  },
  {
    id: "risk_renewal_impact",
    domain: "risk",
    question: "When does risk start to affect renewals?",
    intent: "renewal_readiness",
    primaryAnswerId: "a_risk_renewal_impact",
    variations: [
      "When does risk impact renewal?",
      "How early should we worry before renewal?",
      "Risk vs renewal timeline",
    ],
    keywords: ["renewal", "timeline", "risk impact"],
  },
  {
    id: "risk_document_track",
    domain: "risk",
    question: "How should risk be documented and tracked internally?",
    intent: "documentation",
    primaryAnswerId: "a_risk_document_track",
    variations: [
      "How do we document risk?",
      "How do we track risk internally?",
      "Where do we record risk actions?",
    ],
    keywords: ["document risk", "track risk", "internal notes", "timeline"],
  },

  {
    id: "risk_reanchor_value",
    domain: "risk",
    question: "How do I re-anchor the conversation around value?",
    intent: "customer_comms",
    primaryAnswerId: "a_risk_reanchor_value",
    variations: [
      "How do I re-anchor around value?",
      "How do I talk about value not features?",
      "Customer conversation: value framing",
    ],
    keywords: ["re-anchor", "value", "outcomes", "ROI"],
  },
  {
    id: "risk_document_actions",
    domain: "risk",
    question: "How do I document risk-related actions?",
    intent: "documentation",
    primaryAnswerId: "a_risk_document_actions",
    variations: [
      "How do we document risk actions?",
      "Where do we write what we tried?",
      "How do we keep a risk log?",
    ],
    keywords: ["risk actions", "documentation", "log", "timeline"],
  },

  {
    id: "escalation_prepare_info",
    domain: "risk",
    question: "What information should I prepare before escalating?",
    intent: "prep",
    primaryAnswerId: "a_escalation_prepare_info",
    variations: [
      "What do I prepare before escalation?",
      "Escalation prep checklist",
      "What info is needed for escalation?",
    ],
    keywords: ["prepare", "escalation", "checklist"],
  },
  {
    id: "escalation_who_involved",
    domain: "risk",
    question: "Who needs to be involved in an escalation?",
    intent: "stakeholders",
    primaryAnswerId: "a_escalation_who_involved",
    variations: [
      "Who should be involved in escalation?",
      "Escalation stakeholders",
      "Who joins an escalation call?",
    ],
    keywords: ["who involved", "stakeholders", "escalation"],
  },
  {
    id: "escalation_internal_vs_external",
    domain: "risk",
    question: "How do I communicate escalation internally vs externally?",
    intent: "comms",
    primaryAnswerId: "a_escalation_internal_vs_external",
    variations: [
      "How do I communicate escalation internally?",
      "How do I talk to the customer about escalation?",
      "Internal vs external escalation comms",
    ],
    keywords: ["communicate", "internally", "externally", "escalation"],
  },
  {
    id: "escalation_after",
    domain: "risk",
    question: "What happens after an escalation is initiated?",
    intent: "process",
    primaryAnswerId: "a_escalation_after",
    variations: [
      "What happens after escalation?",
      "After we escalate, what next?",
      "Escalation process after kickoff",
    ],
    keywords: ["after escalation", "next steps", "process"],
  },
];