import type { FollowUp } from "../types/core";

export const FOLLOW_UPS: FollowUp[] = [
  // Onboarding completion
  {
    id: "fu_onb_first_value",
    parentAnswerId: "a_onboarding_completion_primary",
    label: "What counts as first value?",
    intent: "clarify_definition",
    targetAnswerId: "a_fu_onb_first_value",
    targetCanonicalId: "onboarding_completion",
  },
  {
    id: "fu_onb_stalls",
    parentAnswerId: "a_onboarding_completion_primary",
    label: "What if onboarding stalls or is delayed?",
    intent: "corrective_action",
    targetAnswerId: "a_onboarding_stalled_primary",
    targetCanonicalId: "onboarding_stalled",
  },
  {
    id: "fu_onb_to_adoption",
    parentAnswerId: "a_onboarding_completion_primary",
    label: "When do we transition from onboarding to adoption?",
    intent: "lifecycle_transition",
    targetAnswerId: "a_fu_onb_to_adoption",
    targetCanonicalId: "onboarding_completion",
  },
  {
    id: "fu_onb_document_completion",
    parentAnswerId: "a_onboarding_completion_primary",
    label: "How do we document onboarding completion?",
    intent: "documentation",
    targetAnswerId: "a_fu_onb_document_completion",
    targetCanonicalId: "onboarding_completion",
  },

  // Kickoff outcomes
  {
    id: "fu_kickoff_red_flags",
    parentAnswerId: "a_kickoff_outcomes_primary",
    label: "What are common kickoff red flags?",
    intent: "risk_prevention",
    targetAnswerId: "a_fu_kickoff_red_flags",
    targetCanonicalId: "kickoff_outcomes",
  },
  {
    id: "fu_kickoff_document",
    parentAnswerId: "a_kickoff_outcomes_primary",
    label: "What should be documented after the kickoff?",
    intent: "documentation",
    targetAnswerId: "a_fu_kickoff_document",
    targetCanonicalId: "kickoff_outcomes",
  },
  {
    id: "fu_kickoff_success_plan",
    parentAnswerId: "a_kickoff_outcomes_primary",
    label: "How does the kickoff feed into the success plan?",
    intent: "framework_link",
    targetAnswerId: "a_fu_kickoff_success_plan",
    targetCanonicalId: "kickoff_outcomes",
  },
  {
    id: "fu_kickoff_who_involved",
    parentAnswerId: "a_kickoff_outcomes_primary",
    label: "Who needs to be involved in the kickoff call?",
    intent: "stakeholders",
    targetAnswerId: "a_fu_kickoff_who_involved",
    targetCanonicalId: "kickoff_outcomes",
  },

  // Onboarding stalled
  {
    id: "fu_stall_root_cause",
    parentAnswerId: "a_onboarding_stalled_primary",
    label: "How do we identify the root cause of onboarding delays?",
    intent: "diagnosis",
    targetAnswerId: "a_fu_stall_root_cause",
    targetCanonicalId: "onboarding_stalled",
  },
  {
    id: "fu_stall_becomes_risk",
    parentAnswerId: "a_onboarding_stalled_primary",
    label: "When does a delay become a risk?",
    intent: "thresholds",
    targetAnswerId: "a_risk_detection_primary",
    targetCanonicalId: "risk_detection",
  },
  {
    id: "fu_stall_reset_timeline",
    parentAnswerId: "a_onboarding_stalled_primary",
    label: "How do we reset onboarding timelines with the customer?",
    intent: "customer_comms",
    targetAnswerId: "a_fu_stall_reset_timeline",
    targetCanonicalId: "onboarding_stalled",
  },
  {
    id: "fu_stall_escalate",
    parentAnswerId: "a_onboarding_stalled_primary",
    label: "When should onboarding be escalated?",
    intent: "escalation_boundary",
    targetAnswerId: "a_risk_escalation_primary",
    targetCanonicalId: "risk_escalation",
  },

  // Risk detection
  {
    id: "fu_risk_check_first",
    parentAnswerId: "a_risk_detection_primary",
    label: "What should I check first when I suspect risk?",
    intent: "diagnosis",
    targetAnswerId: "a_fu_risk_check_first",
    targetCanonicalId: "risk_detection",
  },
  {
    id: "fu_risk_actions_before_escalation",
    parentAnswerId: "a_risk_detection_primary",
    label: "What actions should I take before escalating?",
    intent: "risk_response",
    targetAnswerId: "a_risk_response_primary",
    targetCanonicalId: "risk_response",
  },
  {
    id: "fu_risk_renewal_impact",
    parentAnswerId: "a_risk_detection_primary",
    label: "When does risk start to affect renewals?",
    intent: "renewal_readiness",
    targetAnswerId: "a_fu_risk_renewal_impact",
    targetCanonicalId: "risk_detection",
  },
  {
    id: "fu_risk_document_track",
    parentAnswerId: "a_risk_detection_primary",
    label: "How should risk be documented and tracked internally?",
    intent: "documentation",
    targetAnswerId: "a_fu_risk_document_track",
    targetCanonicalId: "risk_detection",
  },

  // Risk response
  {
    id: "fu_risk_reanchor_value",
    parentAnswerId: "a_risk_response_primary",
    label: "How do I re-anchor the conversation around value?",
    intent: "customer_comms",
    targetAnswerId: "a_fu_risk_reanchor_value",
    targetCanonicalId: "risk_response",
  },
  {
    id: "fu_risk_involve_leadership",
    parentAnswerId: "a_risk_response_primary",
    label: "When should I involve leadership?",
    intent: "escalation_boundary",
    targetAnswerId: "a_risk_escalation_primary",
    targetCanonicalId: "risk_escalation",
  },
  {
    id: "fu_risk_document_actions",
    parentAnswerId: "a_risk_response_primary",
    label: "How do I document risk-related actions?",
    intent: "documentation",
    targetAnswerId: "a_fu_risk_document_actions",
    targetCanonicalId: "risk_response",
  },

  // Risk escalation
  {
    id: "fu_escalation_prepare_info",
    parentAnswerId: "a_risk_escalation_primary",
    label: "What information should I prepare before escalating?",
    intent: "prep",
    targetAnswerId: "a_fu_escalation_prepare_info",
    targetCanonicalId: "risk_escalation",
  },
  {
    id: "fu_escalation_who_involved",
    parentAnswerId: "a_risk_escalation_primary",
    label: "Who needs to be involved in an escalation?",
    intent: "stakeholders",
    targetAnswerId: "a_fu_escalation_who_involved",
    targetCanonicalId: "risk_escalation",
  },
  {
    id: "fu_escalation_internal_vs_external",
    parentAnswerId: "a_risk_escalation_primary",
    label: "How do I communicate escalation internally vs externally?",
    intent: "comms",
    targetAnswerId: "a_fu_escalation_internal_vs_external",
    targetCanonicalId: "risk_escalation",
  },
  {
    id: "fu_escalation_after",
    parentAnswerId: "a_risk_escalation_primary",
    label: "What happens after an escalation is initiated?",
    intent: "process",
    targetAnswerId: "a_fu_escalation_after",
    targetCanonicalId: "risk_escalation",
  },
];